### ISSUE TITLE
use 03_wbz45x_winc1500_wifiProv and cannot connect iphone 13/14 hot spot

### ISSUE THREAD

**Issue by AngelkingQK** [MicrochipTech/PIC32CXBZ2_WBZ45x_BLE_WINC1500#2]
Hello Sir,
I programed the project into WBZ45x board without coding.
The result is cannot connect my iphone 13/14 hot spot.
UART Log shows as following...

WINC: Initializing...

Welcome to WINC1500 BLE Provisioning Example

BLE Connected..

Accepting Pairing Req

DisplayPass Key:

224565

Pairing Completed Successfully

BLE link is encrypted successfully

Please enter SSID, Passphrase in MBD app.

Auth Type: 2

SSID: CY_Chen

SSID Len: 7

Password: yazz2647

Password Len: 8

Chip ID 1503a0

[nm_spi_init]: chipid (001003a0)

BLE Disconnected..0x16

DriverVerInfo: 0x13301376

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

13301376 13301376 102

WINC1500 Firmware Data:

Firmware Ver: 19.7.7 SVN Rev 19759

Firmware Built at Mar 30 2022 Time 13:32:43

Firmware Min Driver Ver: 19.3DDWINC: Initializing...complete

Wi-Fi Connecting......

**Comment by sankar-mohan** [comment]
Hi @AngelkingQK

Thanks for reporting the issue. 
I haven't tested by connecting WINC1500 Application with iphone 13/14 hot spot.  I've not tried using iPhone 13/14 as hotspot and tried connecting WINC1500 to it. 
Are you able to connect 03_wbz45x_winc1500_wifiProv example to a Wi-Fi Router? Could you please confirm whether the issue only arises while trying to connect to an iPhone 13 hot spot.

**Comment by AngelkingQK** [comment]
Hi @sankar-mohan 
I have tried to connect with Wi-Fi Router, but the WINC1500 still cannot connect.
And then I also have tried those 4 example codes, but only serial bridge is working.

BY the way, I have used WINC1500+SAMD21 and running the TCP Client example.
This WINC1500 can be connected iPhone13/14 hot spot & Wi-Fi Router.

**Comment by sankar-mohan** [comment]
Hi @AngelkingQK 

Please ensure that you are using WBZ451 Curiosity Borad Rev3 Boards.
Due to a change made to the INT pin on the Rev2 board, this application will not run.
If using Rev2 board, please change the INT pin in the application. 
Additionally, while using Rev2 boards, please use an external power supply to power up the board as it might not be able to provide adequate power.

**Comment by AngelkingQK** [comment]
Hi @sankar-mohan,
Thank you, I have used external power supply to power up the board on rev2 board.
It's working.
